version: '3.4'

services:
  gymitrius:
    image: gymitrius
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm start
    environment:
      NODE_ENV: production
    volumes:
       - .:/usr/app
    ports:
      - 3000:3000
